/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface UiLogger {
    'addLogMessage': (type: string, message: string) => void;
    'config': any;
  }
  interface UiLoggerAttributes extends StencilHTMLAttributes {
    'config'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'UiLogger': Components.UiLogger;
  }

  interface StencilIntrinsicElements {
    'ui-logger': Components.UiLoggerAttributes;
  }


  interface HTMLUiLoggerElement extends Components.UiLogger, HTMLStencilElement {}
  var HTMLUiLoggerElement: {
    prototype: HTMLUiLoggerElement;
    new (): HTMLUiLoggerElement;
  };

  interface HTMLElementTagNameMap {
    'ui-logger': HTMLUiLoggerElement
  }

  interface ElementTagNameMap {
    'ui-logger': HTMLUiLoggerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
